bbcodeSettings = {
			nameSpace: "bbcode", // Useful to prevent multi-instances CSS conflict
			markupSet: [
				{name:'Grassetto', key:'B', openWith:'[b]', closeWith:'[/b]'},
				{name:'Corsivo', key:'I', openWith:'[i]', closeWith:'[/i]'},
				{name:'Sottolineato', key:'U', openWith:'[u]', closeWith:'[/u]'},
				{name:'Sbarrato', key:'S', openWith:'[s]', closeWith:'[/s]'},
				{name:'Titolo', key:'H', openWith:'[h]', closeWith:'[/h]'},
				{separator:'---------------' },
				{name:'Immagine', key:'P', replaceWith:'[img][![Inserisci l\'URL dell\'immagine:]!][/img]'}, 
				{name:'Collegamento', key:'L', openWith:'[url=[![Inserisci l\'URL:]!]]', closeWith:'[/url]', placeHolder:'Collegamento atomico...'},
				{separator:'---------------' },
				{name:'Colori', openWith:'[color=[![Colore:]!]]', closeWith:'[/color]', dropMenu: [
				{name:'Giallo', openWith:'[color=yellow]', closeWith:'[/color]', className:"col1-1" },
					{name:'Arancione', openWith:'[color=orange]', closeWith:'[/color]', className:"col1-2" },
					{name:'Rosso', openWith:'[color=red]', closeWith:'[/color]', className:"col1-3" },
					{name:'Blu', openWith:'[color=blue]', closeWith:'[/color]', className:"col2-1" },
					{name:'Viola', openWith:'[color=purple]', closeWith:'[/color]', className:"col2-2" },
					{name:'Verde', openWith:'[color=green]', closeWith:'[/color]', className:"col2-3" },
					{name:'Bianco', openWith:'[color=white]', closeWith:'[/color]', className:"col3-1" },
					{name:'Grigio', openWith:'[color=gray]', closeWith:'[/color]', className:"col3-2" },
					{name:'Nero', openWith:'[color=black]', closeWith:'[/color]', className:"col3-3" }
				]},
			{separator:'---------------' },
			{name:'Lista semplice', openWith:'[list]\n', closeWith:'\n[/list]'}, 
			{name:'Lista ordinata', openWith:'[list=[![Numero da cui iniziare:]!]]\n', closeWith:'\n[/list]'}, 
			{name:'Elemento lista', openWith:'[*] ', closeWith: '[/*]'}, 
			{separator:'---------------' },
			{name:'Citazione', openWith:'[quote]', closeWith:'[/quote]'}, 
			{name:'Cita utente', openWith:'[quote="[![Inserisci il nome utente:]!]"]', closeWith:'[/quote]', placeHolder:'Bla bla bla...'}, 
			{name:'Codice', openWith:'[code]', closeWith:'[/code]'},
			{separator:'---------------' },
			{name:':)', replaceWith:' :)'},
			{name:':|', replaceWith:' :|'},
			{name:':(', replaceWith:' :('},
			{name:':D', replaceWith:' :D'},
			{name:':o', replaceWith:' :o'},
			{name:';)', replaceWith:' ;)'},
			{name:':/', replaceWith:' :/'},
			{name:':p', replaceWith:' :p'},
			{name:':lol:', replaceWith:' :lol:'},
			{name:':mad:', replaceWith:' :mad:'},
			{name:':rolleyes:', replaceWith:' :rolleyes:'},
			{name:':cool:', replaceWith:' :cool:'}
		]};
