bbcodeSettings = {
			nameSpace: "bbcode", // Useful to prevent multi-instances CSS conflict
			markupSet: [
				{name:'Bold', key:'B', openWith:'[b]', closeWith:'[/b]'},
				{name:'Italic', key:'I', openWith:'[i]', closeWith:'[/i]'},
				{name:'Underline', key:'U', openWith:'[u]', closeWith:'[/u]'},
				{name:'Strike-through', key:'S', openWith:'[s]', closeWith:'[/s]'},
				{name:'Heading', key:'H', openWith:'[h]', closeWith:'[/h]'},
				{separator:'---------------' },
				{name:'Image', key:'P', replaceWith:'[img][![Insert image URL:]!][/img]'}, 
				{name:'Link', key:'L', openWith:'[url=[![Insert URL:]!]]', closeWith:'[/url]', placeHolder:'Link description here...'},
				{separator:'---------------' },
				{name:'Colors', openWith:'[color=[![Color code:]!]]', closeWith:'[/color]', dropMenu: [
				{name:'Yellow', openWith:'[color=yellow]', closeWith:'[/color]', className:"col1-1" },
					{name:'Orange', openWith:'[color=orange]', closeWith:'[/color]', className:"col1-2" },
					{name:'Red', openWith:'[color=red]', closeWith:'[/color]', className:"col1-3" },
					{name:'Blue', openWith:'[color=blue]', closeWith:'[/color]', className:"col2-1" },
					{name:'Purple', openWith:'[color=purple]', closeWith:'[/color]', className:"col2-2" },
					{name:'Green', openWith:'[color=green]', closeWith:'[/color]', className:"col2-3" },
					{name:'White', openWith:'[color=white]', closeWith:'[/color]', className:"col3-1" },
					{name:'Gray', openWith:'[color=gray]', closeWith:'[/color]', className:"col3-2" },
					{name:'Black', openWith:'[color=black]', closeWith:'[/color]', className:"col3-3" }
				]},
			{separator:'---------------' },
			{name:'Bullet list', openWith:'[list]\n', closeWith:'\n[/list]'}, 
			{name:'Numbered list', openWith:'[list=[![Starting number:]!]]\n', closeWith:'\n[/list]'}, 
			{name:'List element', openWith:'[*] ', closeWith: '[/*]'}, 
			{separator:'---------------' },
			{name:'Quote', openWith:'[quote]', closeWith:'[/quote]'}, 
			{name:'Quote from user', openWith:'[quote="[![Quoted username:]!]"]', closeWith:'[/quote]', placeHolder:'He said this...'}, 
			{name:'Code', openWith:'[code]', closeWith:'[/code]'},
			{separator:'---------------' },
			{name:':)', replaceWith:' :)'},
			{name:':|', replaceWith:' :|'},
			{name:':(', replaceWith:' :('},
			{name:':D', replaceWith:' :D'},
			{name:':o', replaceWith:' :o'},
			{name:';)', replaceWith:' ;)'},
			{name:':/', replaceWith:' :/'},
			{name:':p', replaceWith:' :p'},
			{name:':lol:', replaceWith:' :lol:'},
			{name:':mad:', replaceWith:' :mad:'},
			{name:':rolleyes:', replaceWith:' :rolleyes:'},
			{name:':cool:', replaceWith:' :cool:'}
		]};
