bbcodeSettings = {
			nameSpace: "bbcode", // Useful to prevent multi-instances CSS conflict
			markupSet: [
				{name:'Fett', key:'B', openWith:'[b]', closeWith:'[/b]'},
				{name:'Kursiv', key:'I', openWith:'[i]', closeWith:'[/i]'},
				{name:'Unterstreichen', key:'U', openWith:'[u]', closeWith:'[/u]'},
				{name:'Durchstreichen', key:'S', openWith:'[s]', closeWith:'[/s]'},
				{name:'Überschrift', key:'H', openWith:'[h]', closeWith:'[/h]'},
				{name:'Spoiler', key:'-', openWith:'[spoiler]', closeWith:'[/spoiler]'},
				{separator:'---------------' },
				{name:'Bild', key:'P', replaceWith:'[img][![Bild-URL einfügen:]!][/img]'}, 
				{name:'Link', key:'L', openWith:'[url=[![URL einfügen:]!]]', closeWith:'[/url]', placeHolder:'Linkbeschreibung hier...'},
				{separator:'---------------' },
				{name:'Farben', openWith:'[color=[![Color code:]!]]', closeWith:'[/color]', dropMenu: [
				{name:'Gelb', openWith:'[color=yellow]', closeWith:'[/color]', className:"col1-1" },
					{name:'Orange', openWith:'[color=orange]', closeWith:'[/color]', className:"col1-2" },
					{name:'Rot', openWith:'[color=red]', closeWith:'[/color]', className:"col1-3" },
					{name:'Blau', openWith:'[color=blue]', closeWith:'[/color]', className:"col2-1" },
					{name:'Violett', openWith:'[color=purple]', closeWith:'[/color]', className:"col2-2" },
					{name:'Grün', openWith:'[color=green]', closeWith:'[/color]', className:"col2-3" },
					{name:'Weiß', openWith:'[color=white]', closeWith:'[/color]', className:"col3-1" },
					{name:'Grau', openWith:'[color=gray]', closeWith:'[/color]', className:"col3-2" },
					{name:'Schwarz', openWith:'[color=black]', closeWith:'[/color]', className:"col3-3" }
				]},
			{separator:'---------------' },
			{name:'Punktliste', openWith:'[list]\n', closeWith:'\n[/list]'}, 
			{name:'Nummernliste', openWith:'[list=[![Startnummer:]!]]\n', closeWith:'\n[/list]'}, 
			{name:'Listenelement', openWith:'[*] ', closeWith: '[/*]'}, 
			{separator:'---------------' },
			{name:'Zitat', openWith:'[quote]', closeWith:'[/quote]'}, 
			{name:'Zitat von User', openWith:'[quote="[![Zitierter Nutzername:]!]"]', closeWith:'[/quote]', placeHolder:'Er schrieb dies...'}, 
			{name:'Code', openWith:'[code]', closeWith:'[/code]'},
			{separator:'---------------' },
			{name:':)', replaceWith:':)'},
			{name:':|', replaceWith:':|'},
			{name:':(', replaceWith:':('},
			{name:':D', replaceWith:':D'},
			{name:':o', replaceWith:':o'},
			{name:';)', replaceWith:';)'},
			{name:':/', replaceWith:':/'},
			{name:':p', replaceWith:':p'},
			{name:':lol:', replaceWith:':lol:'},
			{name:':mad:', replaceWith:':mad:'},

{ dropMenu: [
			{name:':rolleyes:', replaceWith:':rolleyes:', className:"col1-1"},
			{name:':shock:', replaceWith:':shock:', className:"col1-2"},
			{name:':heart:', replaceWith:':heart:', className:"col1-3"},
			{name:':cool:', replaceWith:':cool:', className:"col1-4"},
			{name:':love:', replaceWith:':love:', className:"col1-5"},
			{name:':((', replaceWith:':((', className:"col2-1"},
			{name:':oops:', replaceWith:':oops:', className:"col2-2"},
			{name:':Zzz:', replaceWith:':Zzz:', className:"col2-3"},
			{name:'0:)', replaceWith:'0:)', className:"col2-4"},
			{name:':x', replaceWith:':x', className:"col2-5"},
			{name:':teen:', replaceWith:':teen:', className:"col3-1"},
			{name:':--', replaceWith:':--', className:"col3-2"},
			{name:':*', replaceWith:':*', className:"col3-3"},
			{name:':DD', replaceWith:':DD', className:"col3-4"},
			{name:':shit:', replaceWith:':shit:', className:"col3-5"},
 			{name:':roto:', replaceWith:':roto:', className:"col4-1"},
 			{name:':zank:', replaceWith:':zank:', className:"col4-2"},
 			{name:':voegasm:', replaceWith:':voegasm:', className:"col4-3"},
 			{name:':ugly:', replaceWith:':ugly:', className:"col4-4"},
 			{name:':smoke:', replaceWith:':smoke:', className:"col4-5"},
  ]
}

		]};
